#!/bin/bash -eu

# Static source assertions intentionally contain literal shell syntax.
# shellcheck disable=SC2016

test_dir="$(mktemp -d "${TMPDIR:-/tmp}/teslausb-web-config-test.XXXXXX")"
trap 'rm -rf -- "$test_dir"' EXIT

repo_root="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd)"
configure_web="$repo_root/setup/pi/configure-web.sh"
nginx_config="$repo_root/teslausb-www/teslausb.nginx"
web_sudo="$repo_root/teslausb-www/teslausb-web-sudo"

assert_contains() {
  local file="$1"
  local expected="$2"

  if ! grep -Fq -- "$expected" "$file"
  then
    echo "Expected $file to contain: $expected" >&2
    exit 1
  fi
}

assert_count() {
  local expected_count="$1"
  local pattern="$2"
  local file="$3"
  local actual_count

  actual_count="$(grep -Fc -- "$pattern" "$file" || true)"
  if [ "$actual_count" -ne "$expected_count" ]
  then
    echo "Expected $expected_count occurrences of '$pattern' in $file, got $actual_count" >&2
    exit 1
  fi
}

# Auth is inherited from server scope, including regex locations. Provisioning
# must use bcrypt/stdin and reject incomplete credentials.
assert_count 1 'auth_basic off;' "$nginx_config"
assert_count 1 'auth_basic_user_file /etc/nginx/.htpasswd;' "$nginx_config"
assert_contains "$configure_web" 'WEB_USERNAME and WEB_PASSWORD must both be set'
# shellcheck disable=SC2016 # Assertions intentionally search literal shell source.
assert_contains "$configure_web" 'htpasswd -Bci "$htpasswd_tmp" "$WEB_USERNAME"'
# shellcheck disable=SC2016 # Assertions intentionally search literal shell source.
assert_contains "$configure_web" 'chmod 0640 "$htpasswd_tmp"'

auth_validator_source="$(sed -n '/^validate_web_auth_config() {$/,/^}$/p' "$configure_web")"
eval "$auth_validator_source"
setup_progress() { :; }
unset WEB_USERNAME WEB_PASSWORD
WEB_AUTH_DISABLED=true
validate_web_auth_config
unset WEB_AUTH_DISABLED
if validate_web_auth_config 2>/dev/null
then
  echo "Auth validator accepted missing credentials without an explicit opt-out" >&2
  exit 1
fi
if (WEB_AUTH_DISABLED=maybe; validate_web_auth_config) 2>/dev/null
then
  echo "Auth validator accepted an invalid WEB_AUTH_DISABLED value" >&2
  exit 1
fi
if (WEB_AUTH_DISABLED=true; WEB_USERNAME=user; WEB_PASSWORD='long enough secret'; validate_web_auth_config) 2>/dev/null
then
  echo "Auth validator accepted credentials together with the auth opt-out" >&2
  exit 1
fi
if (WEB_USERNAME=user; WEB_PASSWORD=; validate_web_auth_config) 2>/dev/null
then
  echo "Auth validator accepted a username without a password" >&2
  exit 1
fi
if (WEB_USERNAME=; WEB_PASSWORD=secret; validate_web_auth_config) 2>/dev/null
then
  echo "Auth validator accepted a password without a username" >&2
  exit 1
fi
if (WEB_USERNAME='bad:name'; WEB_PASSWORD=secret; validate_web_auth_config) 2>/dev/null
then
  echo "Auth validator accepted an htpasswd delimiter in the username" >&2
  exit 1
fi
WEB_USERNAME=user
WEB_PASSWORD='correct horse battery staple'
# shellcheck disable=SC2034 # Variable is consumed by the extracted function.
WEB_AUTH_DISABLED=false
validate_web_auth_config
if (WEB_USERNAME=user; WEB_PASSWORD=raspberry; validate_web_auth_config) 2>/dev/null
then
  echo "Auth validator accepted the default Raspberry Pi password" >&2
  exit 1
fi
# shellcheck disable=SC2034 # Variables are consumed by the extracted function.
if (WEB_USERNAME=user; WEB_PASSWORD="$(printf 'x%.0s' {1..73})"; validate_web_auth_config) 2>/dev/null
then
  echo "Auth validator accepted a bcrypt-truncated password" >&2
  exit 1
fi
unset WEB_USERNAME WEB_PASSWORD WEB_AUTH_DISABLED

assert_contains "$configure_web" 'WEB_AUTH_DISABLED cannot be combined with WEB_USERNAME or WEB_PASSWORD'
assert_contains "$configure_web" 'WEB_AUTH_AUTOGENERATED=true'
assert_contains "$configure_web" 'local credential_file=/root/teslausb-web-credentials'
assert_contains "$configure_web" "chmod 0600 \"\$credential_tmp\""
assert_contains "$configure_web" "run 'sudo cat \$credential_file' to retrieve them"
assert_contains "$web_sudo" "readonly declarative_setup='/root/teslausb_setup.json'"
assert_contains "$web_sudo" 'get-ble-vin "$declarative_setup"'

# The root dispatcher parses the helper's ANSI-C-quoted VIN without sourcing
# the configuration. Only a single literal token is accepted.
ble_vin_parser="$(sed -n '/^parse_ble_vin_line() {$/,/^}$/p' "$web_sudo")"
eval "$ble_vin_parser"
for vin_line in \
  'export TESLA_BLE_VIN=5YJ3E1EA7KF317000' \
  "export TESLA_BLE_VIN='5YJ3E1EA7KF317000'" \
  'export TESLA_BLE_VIN="5YJ3E1EA7KF317000"' \
  "export TESLA_BLE_VIN=\$'5yj3e1ea7kf317000'"
do
  TESLA_BLE_VIN=
  parse_ble_vin_line "$vin_line"
  [ "$TESLA_BLE_VIN" = '5YJ3E1EA7KF317000' ] || {
    echo "BLE VIN parser rejected a supported literal form" >&2
    exit 1
  }
done
for vin_line in \
  "export TESLA_BLE_VIN=\$'5YJ3E1EA7KF317000'\$(touch /tmp/pwn)" \
  "export TESLA_BLE_VIN=\$'5YJ3E1EA7KF317000''suffix'" \
  "export TESLA_BLE_VIN=\$'5YJ3E1EA7KF31700\\x30'" \
  'export TESLA_BLE_VIN=5YJ3E1EA7KF317000 # comment'
do
  TESLA_BLE_VIN=
  if parse_ble_vin_line "$vin_line"
  then
    echo "BLE VIN parser accepted a non-literal or concatenated value" >&2
    exit 1
  fi
done

# Media/index locations stay in place, while only active file extensions get
# attachment handling. same-origin is required by the legacy UI switch.
assert_contains "$nginx_config" 'location /TeslaCam/ {'
assert_contains "$nginx_config" 'fancyindex on;'
assert_contains "$nginx_config" 'location ~* ^/(?:fs|TeslaCam)/.*\.(?:s?html?|xhtml|svgz?|xml|xsl|xslt|m?js)$ {'
assert_contains "$nginx_config" 'add_header Content-Disposition "attachment" always;'
assert_contains "$nginx_config" 'add_header Referrer-Policy "same-origin" always;'
assert_contains "$nginx_config" 'add_header Cross-Origin-Resource-Policy "same-origin" always;'

# Installed ES modules must work even with older OS MIME tables. Their narrow
# location adds no auth/header override; actual HTTP behavior is exercised by
# test_modern_static_http.py when nginx is installed.
assert_contains "$nginx_config" 'location ~ ^/modern/.*\.mjs$ {'
assert_count 1 'types { application/javascript mjs; }' "$nginx_config"
assert_contains "$configure_web" 'cp -r "$SOURCE_DIR/teslausb-www/html/." /var/www/html/'

# Host validation is server-wide (not just CGI), and the private IPv6 rules
# require a literal colon so a public DNS name beginning with fd/fc/fe cannot
# masquerade as a local address.
# shellcheck disable=SC2016 # Assertions intentionally search literal nginx source.
assert_contains "$nginx_config" 'map $host $teslausb_host_allowed {'
# shellcheck disable=SC2016 # Assertions intentionally search literal nginx source.
assert_contains "$nginx_config" 'if ($teslausb_host_allowed = 0) {'
assert_contains "$nginx_config" '~^f[cd][0-9a-f:]*:[0-9a-f:]+$ 1;'
if grep -Eq '^[[:space:]]*"?fd-attacker\.example' "$nginx_config"
then
  echo "Static Host policy unexpectedly permits fd-attacker.example" >&2
  exit 1
fi
assert_contains "$nginx_config" 'location ~ ^/api/v1(?:/.*)?$ {'
assert_contains "$nginx_config" 'fastcgi_param SCRIPT_FILENAME /var/www/html/cgi-bin/api-v1.sh;'
# shellcheck disable=SC2016 # Assertions intentionally search literal nginx source.
assert_contains "$nginx_config" 'fastcgi_param PATH_INFO $uri;'

# External UI downloads are opt-in, release/checksum pinned, size-bounded, and
# switched only after extraction into a content-addressed release directory.
# shellcheck disable=SC2016 # Assertions intentionally search literal shell source.
assert_contains "$configure_web" 'local webui_release="${WEBUI_RELEASE:-}"'
# shellcheck disable=SC2016 # Assertions intentionally search literal shell source.
assert_contains "$configure_web" 'local webui_expected_sha256="${WEBUI_SHA256:-}"'
assert_contains "$configure_web" 'requires both WEBUI_RELEASE and WEBUI_SHA256'
assert_contains "$configure_web" '--max-filesize 67108864'
if grep -Fq 'releases/latest/download/teslausb-ui.tgz' "$configure_web" ||
   grep -Fq 'verification=sha256-recorded' "$configure_web"
then
  echo "WebUI installer still contains an unpinned download path" >&2
  exit 1
fi
assert_contains "$configure_web" 'webui_verification=sha256-pinned'
# shellcheck disable=SC2016 # Assertions intentionally search literal shell source.
assert_contains "$configure_web" 'mv -Tf "$webui_next_link" /var/www/html/new'
assert_contains "$configure_web" '-path /var/www/html/new -prune'
assert_contains "$configure_web" "find /var/www/html/cgi-bin -xdev -type f -name '*.sh' -exec chmod 0755"

# Allowed-host parsing is safe when the optional setting is unset and rejects
# injection while accepting explicit local/custom names and IPv6 literals.
for function_name in validate_ipv6_literal validate_ipv4_literal \
  validate_dns_hostname normalize_allowed_web_host prepare_allowed_web_hosts
do
  eval "$(sed -n "/^${function_name}() {$/,/^}$/p" "$configure_web")"
done
# shellcheck disable=SC2034 # Array is consumed by the extracted function.
declare -a TESLAUSB_ALLOWED_WEB_HOSTS=()
TESLAUSB_FASTCGI_ALLOWED_HOSTS=
# shellcheck disable=SC2034 # Variable is consumed by the extracted function.
TESLAUSB_HOSTNAME=teslausb
unset WEB_ALLOWED_HOSTS
prepare_allowed_web_hosts
[ "$TESLAUSB_FASTCGI_ALLOWED_HOSTS" = teslausb ]
if normalize_allowed_web_host 'bad.example;include' > /dev/null 2>&1
then
  echo "Allowed-host validator accepted nginx directive injection" >&2
  exit 1
fi
[ "$(normalize_allowed_web_host '[fd00::1]')" = 'fd00::1' ]

# Exercise the archive validator directly with safe, traversing, and symlinked
# archives. Extracting just this function avoids running the root setup script.
validator_source="$(sed -n '/^validate_webui_archive() {$/,/^}$/p' "$configure_web")"
eval "$validator_source"

if ! tar --version 2>&1 | grep -q 'GNU tar'
then
  echo "web configuration static tests passed; archive tests require GNU tar"
  exit 0
fi

mkdir -p "$test_dir/safe/new"
printf '<!doctype html>\n' > "$test_dir/safe/new/index.html"
tar -C "$test_dir/safe" -czf "$test_dir/safe.tgz" new
validate_webui_archive "$test_dir/safe.tgz" \
  "$test_dir/safe.list" "$test_dir/safe.verbose"

mkdir -p "$test_dir/link/new"
printf '<!doctype html>\n' > "$test_dir/link/new/index.html"
ln -s index.html "$test_dir/link/new/linked-index.html"
tar -C "$test_dir/link" -czf "$test_dir/link.tgz" new
if validate_webui_archive "$test_dir/link.tgz" \
     "$test_dir/link.list" "$test_dir/link.verbose" 2>/dev/null
then
  echo "Archive validator accepted a symbolic link" >&2
  exit 1
fi

mkdir -p "$test_dir/outside"
printf 'unexpected\n' > "$test_dir/outside/file.txt"
tar -C "$test_dir/outside" -czf "$test_dir/outside.tgz" file.txt
if validate_webui_archive "$test_dir/outside.tgz" \
     "$test_dir/outside.list" "$test_dir/outside.verbose" 2>/dev/null
then
  echo "Archive validator accepted a path outside new/" >&2
  exit 1
fi

echo "web configuration security tests passed"
