server {
    listen 80;
    listen [::]:80;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ =404;
    }

    location /api/ {
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_pass http://api:8080;
    }

    location = /cgi-bin/videolist.sh {
        proxy_pass http://api:8080/api/v1/local/videolist;
    }

    location = /cgi-bin/config.sh {
        proxy_pass http://api:8080/api/v1/local/config;
    }

    location = /cgi-bin/status.sh {
        proxy_pass http://api:8080/api/v1/local/status;
    }

    location /TeslaCam/ {
        alias /data/TeslaCam/;
        autoindex on;
    }
}
