#!/bin/bash -eu

if [[ ( -z "${TESLAFI_API_TOKEN:+x}" ) && ( -z "${TESSIE_API_TOKEN:+x}" ) ]]
then
  log "Not keeping car awake using Sentry Mode via TeslaFi or Tessie."
else
  case "${SENTRY_CASE}" in
    1)
      # Sentry Mode should already be enabled
      log "TeslaFi/Tessie: Skip sending command to enable Sentry Mode."
      ;;
    2)
      if [[ ( -n "${TESLAFI_API_TOKEN:+x}" ) ]]
      # Use TeslaFi API to enable Sentry Mode
      then
        curl -s -H "Authorization: Bearer $TESLAFI_API_TOKEN" "https://www.teslafi.com/feed.php?command=set_sentry_mode&sentryMode=true&noWake=true"
        log "TeslaFi: Command sent to enable Sentry Mode."
      fi

      if [[ -n "${TESSIE_API_TOKEN:+x}" ]]
      # Use Tessie API to enable Sentry Mode
      then
        http_response=$(curl -s -w "%{http_code}" \
          -H "Authorization: Bearer $TESSIE_API_TOKEN" \
          -H "Accept: application/json" \
          -H "User-Agent: github.com/marcone/teslausb" \
          "https://api.tessie.com/$TESSIE_VIN/command/enable_sentry")
              
        log "Tessie: Command sent to enable Sentry Mode."
        # Extract HTTP status code
        http_status="${http_response: -3}"
        
        # Extract response body (excluding status code)
        response_body="${http_response:0:${#http_response}-3}"
        
        # Check if HTTP status code is not 200 (OK)
        if [ "$http_status" != "200" ]
        then
          # Log an error
          log "Tessie: Failed to set Sentry Mode. Check your TESSIE_API_TOKEN and TESSIE_VIN are set correctly. If they are, your car may not have a good connection."
        else
          # Check if the response is in JSON format
          if ! jq -e . >/dev/null 2>&1 <<<"$response_body"
          then
            log "Tessie: Failed to set Sentry Mode. Response data: $response_body"
          else
            # Parse JSON and check if "result" is true
            result=$(jq -r '.result' <<<"$response_body")
            if [[ "$result" != "true" ]]
            then
              log "Tessie: Failed to set Sentry Mode. Response data: $response_body"
            fi
          fi
        fi
      fi
      ;;
    *)
      log "Invalid or no SENTRY_CASE defined."
      ;;
  esac
fi
